{
 "title": "Nuclei dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT s.severity, COUNT(*) AS count\nFROM scans s\nwhere s.severity == 'critical' AND s.timestamp >= $__from AND s.timestamp < $__to",
     "rawQueryText": "SELECT s.severity, COUNT(*) AS count\nFROM scans s\nwhere s.severity == 'critical' AND s.timestamp >= $__from AND s.timestamp < $__to",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Severity count",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 22, "x": 2, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT s.severity, COUNT(*) AS count\nFROM scans s\nWHERE s.timestamp >= $__from AND s.timestamp < $__to\nGROUP BY s.severity",
     "rawQueryText": "SELECT s.severity, COUNT(*) AS count\nFROM scans s\nWHERE s.timestamp >= $__from AND s.timestamp < $__to\nGROUP BY s.severity",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT s.severity, COUNT(*) AS count\nFROM scans s\nwhere s.severity == 'high' AND s.timestamp >= $__from AND s.timestamp < $__to",
     "rawQueryText": "SELECT s.severity, COUNT(*) AS count\nFROM scans s\nwhere s.severity == 'high' AND s.timestamp >= $__from AND s.timestamp < $__to",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT s.severity, COUNT(*) AS count\nFROM scans s\nwhere s.severity == 'medium' AND s.timestamp >= $__from AND s.timestamp < $__to",
     "rawQueryText": "SELECT s.severity, COUNT(*) AS count\nFROM scans s\nwhere s.severity == 'medium' AND s.timestamp >= $__from AND s.timestamp < $__to",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Critical",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT s.signature, s.hostname, s.ip, s.port\nFROM scans s\nWHERE s.severity == 'critical' AND s.timestamp >= $__from AND s.timestamp < $__to",
     "rawQueryText": "SELECT s.signature, s.hostname, s.ip, s.port\nFROM scans s\nWHERE s.severity == 'critical' AND s.timestamp >= $__from AND s.timestamp < $__to",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "High",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT s.signature, s.hostname, s.ip, s.port\nFROM scans s\nWHERE s.severity == 'high' AND s.timestamp >= $__from AND s.timestamp < $__to",
     "rawQueryText": "SELECT s.signature, s.hostname, s.ip, s.port\nFROM scans s\nWHERE s.severity == 'high' AND s.timestamp >= $__from AND s.timestamp < $__to",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Most frequent host",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT s.hostname, COUNT(*) AS count\nFROM scans s\nWHERE s.timestamp >= $__from AND s.timestamp < $__to\nGROUP BY s.hostname order by count DESC ",
     "rawQueryText": "SELECT s.hostname, COUNT(*) AS count\nFROM scans s\nWHERE s.timestamp >= $__from AND s.timestamp < $__to\nGROUP BY s.hostname order by count DESC ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Medium",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "queryText": "SELECT s.signature, s.hostname, s.ip, s.port\nFROM scans s\nWHERE s.severity == 'medium' AND s.timestamp >= $__from AND s.timestamp < $__to",
     "rawQueryText": "SELECT s.signature, s.hostname, s.ip, s.port\nFROM scans s\nWHERE s.severity == 'medium' AND s.timestamp >= $__from AND s.timestamp < $__to",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Nuclei Scan",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "queryText": "SELECT s.severity, s.ip, s.hostname, s.port, s.signature, s.extracted\nFROM scans s\nWHERE s.timestamp >= $__from AND s.timestamp < $__to\n",
     "rawQueryText": "SELECT s.severity, s.ip, s.hostname, s.port, s.signature, s.extracted\nFROM scans s\nWHERE s.timestamp >= $__from AND s.timestamp < $__to\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}